package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bank generated by hbm2java
 */
public class Bank  implements java.io.Serializable {


     private Integer idbank;
     private String bankName;
     private Set doctors = new HashSet(0);

    public Bank() {
    }

    public Bank(String bankName, Set doctors) {
       this.bankName = bankName;
       this.doctors = doctors;
    }
   
    public Integer getIdbank() {
        return this.idbank;
    }
    
    public void setIdbank(Integer idbank) {
        this.idbank = idbank;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public Set getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set doctors) {
        this.doctors = doctors;
    }




}


