package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DoctorHasPatient generated by hbm2java
 */
public class DoctorHasPatient  implements java.io.Serializable {


     private Integer id;
     private Doctor doctor;
     private Patient patient;
     private Status status;
     private Date startDate;
     private Date endDate;
     private Set sugarrates = new HashSet(0);

    public DoctorHasPatient() {
    }

	
    public DoctorHasPatient(Doctor doctor, Patient patient, Status status) {
        this.doctor = doctor;
        this.patient = patient;
        this.status = status;
    }
    public DoctorHasPatient(Doctor doctor, Patient patient, Status status, Date startDate, Date endDate, Set sugarrates) {
       this.doctor = doctor;
       this.patient = patient;
       this.status = status;
       this.startDate = startDate;
       this.endDate = endDate;
       this.sugarrates = sugarrates;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getSugarrates() {
        return this.sugarrates;
    }
    
    public void setSugarrates(Set sugarrates) {
        this.sugarrates = sugarrates;
    }




}


