package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private int userIduser;
     private Bank bank;
     private Hospital hospital;
     private User user;
     private String firstName;
     private String lastName;
     private String mobile;
     private Double tipPayment;
     private Long accountNumber;
     private String accountName;
     private Set doctorHasPatients = new HashSet(0);
     private Set dailytips = new HashSet(0);

    public Doctor() {
    }

	
    public Doctor(Bank bank, User user) {
        this.bank = bank;
        this.user = user;
    }
    public Doctor(Bank bank, Hospital hospital, User user, String firstName, String lastName, String mobile, Double tipPayment, Long accountNumber, String accountName, Set doctorHasPatients, Set dailytips) {
       this.bank = bank;
       this.hospital = hospital;
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.mobile = mobile;
       this.tipPayment = tipPayment;
       this.accountNumber = accountNumber;
       this.accountName = accountName;
       this.doctorHasPatients = doctorHasPatients;
       this.dailytips = dailytips;
    }
   
    public int getUserIduser() {
        return this.userIduser;
    }
    
    public void setUserIduser(int userIduser) {
        this.userIduser = userIduser;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Double getTipPayment() {
        return this.tipPayment;
    }
    
    public void setTipPayment(Double tipPayment) {
        this.tipPayment = tipPayment;
    }
    public Long getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(Long accountNumber) {
        this.accountNumber = accountNumber;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public Set getDoctorHasPatients() {
        return this.doctorHasPatients;
    }
    
    public void setDoctorHasPatients(Set doctorHasPatients) {
        this.doctorHasPatients = doctorHasPatients;
    }
    public Set getDailytips() {
        return this.dailytips;
    }
    
    public void setDailytips(Set dailytips) {
        this.dailytips = dailytips;
    }




}


