package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hospital generated by hbm2java
 */
public class Hospital  implements java.io.Serializable {


     private Integer idhospital;
     private String hospital;
     private Set doctors = new HashSet(0);

    public Hospital() {
    }

    public Hospital(String hospital, Set doctors) {
       this.hospital = hospital;
       this.doctors = doctors;
    }
   
    public Integer getIdhospital() {
        return this.idhospital;
    }
    
    public void setIdhospital(Integer idhospital) {
        this.idhospital = idhospital;
    }
    public String getHospital() {
        return this.hospital;
    }
    
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }
    public Set getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set doctors) {
        this.doctors = doctors;
    }




}


