package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paidstatus generated by hbm2java
 */
public class Paidstatus  implements java.io.Serializable {


     private Integer idpaidStatus;
     private String paidStatus;
     private Set tippayments = new HashSet(0);

    public Paidstatus() {
    }

    public Paidstatus(String paidStatus, Set tippayments) {
       this.paidStatus = paidStatus;
       this.tippayments = tippayments;
    }
   
    public Integer getIdpaidStatus() {
        return this.idpaidStatus;
    }
    
    public void setIdpaidStatus(Integer idpaidStatus) {
        this.idpaidStatus = idpaidStatus;
    }
    public String getPaidStatus() {
        return this.paidStatus;
    }
    
    public void setPaidStatus(String paidStatus) {
        this.paidStatus = paidStatus;
    }
    public Set getTippayments() {
        return this.tippayments;
    }
    
    public void setTippayments(Set tippayments) {
        this.tippayments = tippayments;
    }




}


