package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sugarrate generated by hbm2java
 */
public class Sugarrate  implements java.io.Serializable {


     private Integer idsugarrate;
     private DoctorHasPatient doctorHasPatient;
     private String date;
     private Double sugarRate;
     private String message;
     private Boolean isRead;
     private Set healthtips = new HashSet(0);
     private Set tippayments = new HashSet(0);

    public Sugarrate() {
    }

	
    public Sugarrate(DoctorHasPatient doctorHasPatient) {
        this.doctorHasPatient = doctorHasPatient;
    }
    public Sugarrate(DoctorHasPatient doctorHasPatient, String date, Double sugarRate, String message, Boolean isRead, Set healthtips, Set tippayments) {
       this.doctorHasPatient = doctorHasPatient;
       this.date = date;
       this.sugarRate = sugarRate;
       this.message = message;
       this.isRead = isRead;
       this.healthtips = healthtips;
       this.tippayments = tippayments;
    }
   
    public Integer getIdsugarrate() {
        return this.idsugarrate;
    }
    
    public void setIdsugarrate(Integer idsugarrate) {
        this.idsugarrate = idsugarrate;
    }
    public DoctorHasPatient getDoctorHasPatient() {
        return this.doctorHasPatient;
    }
    
    public void setDoctorHasPatient(DoctorHasPatient doctorHasPatient) {
        this.doctorHasPatient = doctorHasPatient;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getSugarRate() {
        return this.sugarRate;
    }
    
    public void setSugarRate(Double sugarRate) {
        this.sugarRate = sugarRate;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Boolean getIsRead() {
        return this.isRead;
    }
    
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }
    public Set getHealthtips() {
        return this.healthtips;
    }
    
    public void setHealthtips(Set healthtips) {
        this.healthtips = healthtips;
    }
    public Set getTippayments() {
        return this.tippayments;
    }
    
    public void setTippayments(Set tippayments) {
        this.tippayments = tippayments;
    }




}


