package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Status status;
     private String emal;
     private String password;
     private Date regDate;
     private Doctor doctor;
     private Set userloginlogs = new HashSet(0);
     private Patient patient;

    public User() {
    }

	
    public User(Status status) {
        this.status = status;
    }
    public User(Status status, String emal, String password, Date regDate, Doctor doctor, Set userloginlogs, Patient patient) {
       this.status = status;
       this.emal = emal;
       this.password = password;
       this.regDate = regDate;
       this.doctor = doctor;
       this.userloginlogs = userloginlogs;
       this.patient = patient;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getEmal() {
        return this.emal;
    }
    
    public void setEmal(String emal) {
        this.emal = emal;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Set getUserloginlogs() {
        return this.userloginlogs;
    }
    
    public void setUserloginlogs(Set userloginlogs) {
        this.userloginlogs = userloginlogs;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }




}


