package Model.DB;
// Generated 24-Dec-2015 11:17:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userloginlog generated by hbm2java
 */
public class Userloginlog  implements java.io.Serializable {


     private Integer iduserLoginlog;
     private User user;
     private Date logedIn;

    public Userloginlog() {
    }

	
    public Userloginlog(User user) {
        this.user = user;
    }
    public Userloginlog(User user, Date logedIn) {
       this.user = user;
       this.logedIn = logedIn;
    }
   
    public Integer getIduserLoginlog() {
        return this.iduserLoginlog;
    }
    
    public void setIduserLoginlog(Integer iduserLoginlog) {
        this.iduserLoginlog = iduserLoginlog;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getLogedIn() {
        return this.logedIn;
    }
    
    public void setLogedIn(Date logedIn) {
        this.logedIn = logedIn;
    }




}


